import { encryptPassword } from '../../../utils/encrypt';

export const SeedData: any[] = [
  {
    id: '2255a2cf-6e3d-4188-b552-2117b4a40e6d',
    first_name: 'Admin',
    last_name: 'Pusat',
    email: 'user@admin.com',
    username: 'admin',
    password: encryptPassword('secret'),
    // branch_id: null,
    avatar: '',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 'ec8212cb-cb66-4237-8eb1-f5e331dd68b2',
    first_name: 'Branch',
    last_name: 'Manager',
    email: 'manager@branch.com',
    username: 'branchmanager',
    password: encryptPassword('secret'),
    // branch_id: 'fefd2094-644c-4666-8c21-41d33ffb2f8a',
    avatar: '',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 'b4634599-f590-4725-a5fe-9f31f21c6505',
    first_name: 'Branch HR',
    last_name: 'Payroll',
    email: 'hrp@branch.com',
    username: 'branchpayroll',
    password: encryptPassword('secret'),
    // branch_id: 'fefd2094-644c-4666-8c21-41d33ffb2f8a',
    avatar: '',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '37fd635b-e2c9-431d-9072-d8f5056786d8',
    first_name: 'Branch HR',
    last_name: 'Attendance',
    email: 'hra@branch.com',
    username: 'branchattendance',
    password: encryptPassword('secret'),
    // branch_id: 'fefd2094-644c-4666-8c21-41d33ffb2f8a',
    avatar: '',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '3b774351-a593-4c8c-b799-f84a25635e6c',
    first_name: 'General',
    last_name: 'Manager',
    email: 'manager@general.com',
    username: 'generalmanager',
    password: encryptPassword('secret'),
    // branch_id: null,
    avatar: '',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 'f54957fb-4a65-4444-9ec4-4f7e22667865',
    first_name: 'General HR',
    last_name: 'Payroll',
    email: 'hrp@general.com',
    username: 'generalpayroll',
    password: encryptPassword('secret'),
    // branch_id: null,
    avatar: '',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '4c6c1e1d-1bb3-4b67-b00b-367e97327ec4',
    first_name: 'Branch HR',
    last_name: 'Attendance',
    email: 'hra@general.com',
    username: 'generalattendance',
    password: encryptPassword('secret'),
    // branch_id: null,
    avatar: '',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: '01f72448-4d2e-4005-9bee-e949f0bb8ba3',
    first_name: 'Owner',
    last_name: '',
    email: 'owner@mail.com',
    username: 'owner',
    password: encryptPassword('secret'),
    // branch_id: null,
    avatar: '',
    created_at: new Date(),
    updated_at: new Date(),
  },
];