export const SeedData: any[] = [
  {
    // office - shift pagi
    id: '15870fc6-8f14-4274-873d-512b93965222',
    name: 'Shift Pagi',
    base_salary: '2400000',
    schedule: {
      schedules: [
        {
          value: 0,
          duration: '1',
          active: false,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: true,
        },
        {
          value: 1,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: true,
        },
        {
          value: 2,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: true,
        },
        {
          value: 3,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: true,
        },
        {
          value: 4,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: true,
        },
        {
          value: 5,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: true,
        },
        {
          value: 6,
          duration: '1',
          active: false,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: true,
        },
      ],
    },
    department_id: '9f51aac9-8891-406f-821f-1a58f7eb9804',
  },
  {
    // toko mingguan - shift pagi
    id: '49437c28-127e-45fb-b258-95793d8d101a',
    name: 'Shift Pagi',
    base_salary: '2400000',
    schedule: {
      schedules: [
        {
          value: 0,
          duration: '1',
          active: false,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 1,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 2,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 3,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 4,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 5,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 6,
          duration: '1',
          active: false,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
      ],
    },
    department_id: 'a6c011ea-8ead-4da2-a90a-85e2535bdac5',
  },
  {
    // toko bulanan - shift pagi
    id: 'a64cc613-b252-41de-bb05-bd7a60500144',
    name: 'Shift Pagi',
    base_salary: '2400000',
    schedule: {
      schedules: [
        {
          value: 0,
          duration: '1',
          active: false,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 1,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 2,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 3,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 4,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 5,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 6,
          duration: '1',
          active: false,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: null,
          start_one: '08:00',
          start_two: '16:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
      ],
    },
    department_id: '8572a5bd-4821-4739-8b00-218289ca2ef8',
  },
  {
    // toko bulanan - shift siang
    id: 'f16bb98a-601d-4045-ad5b-2e27ea5c16c2',
    name: 'Shift Siang',
    base_salary: '2400000',
    schedule: {
      schedules: [
        {
          value: 0,
          duration: '1',
          active: false,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '11:00 - 21:00',
          end: null,
          start_one: '11:00',
          start_two: '21:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 1,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '11:00 - 21:00',
          end: null,
          start_one: '11:00',
          start_two: '21:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 2,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '11:00 - 21:00',
          end: null,
          start_one: '11:00',
          start_two: '21:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 3,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '11:00 - 21:00',
          end: null,
          start_one: '11:00',
          start_two: '21:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 4,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '11:00 - 21:00',
          end: null,
          start_one: '11:00',
          start_two: '21:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 5,
          duration: '1',
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '11:00 - 21:00',
          end: null,
          start_one: '11:00',
          start_two: '21:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
        {
          value: 6,
          duration: '1',
          active: false,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '11:00 - 21:00',
          end: null,
          start_one: '11:00',
          start_two: '21:00',
          end_one: '',
          end_two: '',
          flexible_break: true,
        },
      ],
    },
    department_id: '8572a5bd-4821-4739-8b00-218289ca2ef8',
  },
  {
    // produksi
    id: '1b1cee07-d9ba-44a6-a96a-3b09f280b48f',
    name: 'Golongan 1',
    base_salary: '2400000',
    schedule: {
      schedules: [
        {
          value: 0,
          active: false,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: '12:00 - 13:00',
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: false,
        },
        {
          value: 1,
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: '12:00 - 13:00',
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: false,
        },
        {
          value: 2,
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: '12:00 - 13:00',
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: false,
        },
        {
          value: 3,
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: '12:00 - 13:00',
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: false,
        },
        {
          value: 4,
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: '12:00 - 13:00',
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: false,
        },
        {
          value: 5,
          active: true,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: '12:00 - 13:00',
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: false,
        },
        {
          value: 6,
          active: false,
          modal_start_one: false,
          modal_start_two: false,
          modal_end_one: false,
          modal_end_two: false,
          start: '08:00 - 16:00',
          end: '12:00 - 13:00',
          start_one: '08:00',
          start_two: '16:00',
          end_one: '12:00',
          end_two: '13:00',
          flexible_break: false,
        },
      ],
    },
    department_id: '81ac066f-2bf9-4bab-b4a5-675d5cc6096c',
  },
];
