import {MigrationInterface, QueryRunner} from 'typeorm';

export class ChangeAttendaceMetaColumnType1571818221977 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query('ALTER TABLE `groups` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `groups` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `groups` CHANGE `base_salary` `base_salary` varchar(15) NULL', undefined);
        await queryRunner.query('ALTER TABLE `groups` CHANGE `week_salary` `week_salary` varchar(15) NULL', undefined);
        await queryRunner.query('ALTER TABLE `groups` CHANGE `day_salary` `day_salary` varchar(15) NULL', undefined);
        await queryRunner.query('ALTER TABLE `groups` DROP COLUMN `schedule`', undefined);
        await queryRunner.query('ALTER TABLE `groups` ADD `schedule` json NOT NULL', undefined);
        await queryRunner.query('ALTER TABLE `positions` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `positions` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `positions` CHANGE `bonus` `bonus` varchar(15) NULL', undefined);
        await queryRunner.query('ALTER TABLE `areas` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `areas` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `areas` CHANGE `bonus` `bonus` varchar(15) NULL', undefined);
        await queryRunner.query('ALTER TABLE `account_permissions` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `account_permissions` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `permissions` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `permissions` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `role_permissions` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `role_permissions` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `roles` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `roles` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `roles` CHANGE `description` `description` varchar(255) NULL', undefined);
        await queryRunner.query('ALTER TABLE `account_roles` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `account_roles` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `accounts` DROP FOREIGN KEY `FK_3ab689e515e134445a81873f87b`', undefined);
        await queryRunner.query('ALTER TABLE `accounts` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `accounts` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `accounts` CHANGE `last_name` `last_name` varchar(255) NULL', undefined);
        await queryRunner.query('ALTER TABLE `accounts` CHANGE `avatar` `avatar` varchar(255) NULL', undefined);
        await queryRunner.query('ALTER TABLE `accounts` CHANGE `branch_id` `branch_id` varchar(255) NULL', undefined);
        await queryRunner.query('ALTER TABLE `branchs` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `branchs` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `branchs` CHANGE `address` `address` text NULL', undefined);
        await queryRunner.query('ALTER TABLE `branchs` CHANGE `postal_code` `postal_code` varchar(6) NULL', undefined);
        await queryRunner.query('ALTER TABLE `branchs` CHANGE `telp` `telp` varchar(15) NULL', undefined);
        await queryRunner.query('ALTER TABLE `departments` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `departments` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `payslips` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `payslips` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `payslips` DROP COLUMN `deduction`', undefined);
        await queryRunner.query('ALTER TABLE `payslips` ADD `deduction` json NOT NULL', undefined);
        await queryRunner.query('ALTER TABLE `payslips` DROP COLUMN `reward`', undefined);
        await queryRunner.query('ALTER TABLE `payslips` ADD `reward` json NOT NULL', undefined);
        await queryRunner.query('ALTER TABLE `payslips` DROP COLUMN `meta`', undefined);
        await queryRunner.query('ALTER TABLE `payslips` ADD `meta` json NOT NULL', undefined);
        await queryRunner.query('ALTER TABLE `leaves` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `leaves` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `reward_deductions` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `reward_deductions` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `employees` DROP FOREIGN KEY `FK_678a3540f843823784b0fe4a4f2`', undefined);
        await queryRunner.query('ALTER TABLE `employees` DROP FOREIGN KEY `FK_4d493f3a20ddc4d8faf6078bf95`', undefined);
        await queryRunner.query('ALTER TABLE `employees` DROP FOREIGN KEY `FK_37fe5168e0e0d65295042d47ea4`', undefined);
        await queryRunner.query('ALTER TABLE `employees` DROP FOREIGN KEY `FK_8b14204e8af5e371e36b8c11e1b`', undefined);
        await queryRunner.query('ALTER TABLE `employees` DROP FOREIGN KEY `FK_43d76ca7eecf9373241e2e890fb`', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `address` `address` text NULL', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `active_date` `active_date` datetime NULL', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `department_id` `department_id` varchar(255) NULL', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `group_id` `group_id` varchar(255) NULL', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `area_id` `area_id` varchar(255) NULL', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `position_id` `position_id` varchar(255) NULL', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `created_by` `created_by` varchar(255) NULL', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `bpjs_id` `bpjs_id` varchar(20) NULL', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `npwp_id` `npwp_id` varchar(20) NULL', undefined);
        await queryRunner.query('ALTER TABLE `attendances` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `attendances` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `attendances` CHANGE `meta` `meta` json NULL', undefined);
        await queryRunner.query('ALTER TABLE `reports` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `reports` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `requests` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `requests` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `rules` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `rules` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `rules` CHANGE `description` `description` text NULL', undefined);
        await queryRunner.query('ALTER TABLE `schedules` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `schedules` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)', undefined);
        await queryRunner.query('ALTER TABLE `accounts` ADD CONSTRAINT `FK_3ab689e515e134445a81873f87b` FOREIGN KEY (`branch_id`) REFERENCES `branchs`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `employees` ADD CONSTRAINT `FK_678a3540f843823784b0fe4a4f2` FOREIGN KEY (`department_id`) REFERENCES `departments`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `employees` ADD CONSTRAINT `FK_4d493f3a20ddc4d8faf6078bf95` FOREIGN KEY (`group_id`) REFERENCES `groups`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `employees` ADD CONSTRAINT `FK_37fe5168e0e0d65295042d47ea4` FOREIGN KEY (`area_id`) REFERENCES `areas`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `employees` ADD CONSTRAINT `FK_8b14204e8af5e371e36b8c11e1b` FOREIGN KEY (`position_id`) REFERENCES `positions`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `employees` ADD CONSTRAINT `FK_43d76ca7eecf9373241e2e890fb` FOREIGN KEY (`created_by`) REFERENCES `accounts`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query('ALTER TABLE `employees` DROP FOREIGN KEY `FK_43d76ca7eecf9373241e2e890fb`', undefined);
        await queryRunner.query('ALTER TABLE `employees` DROP FOREIGN KEY `FK_8b14204e8af5e371e36b8c11e1b`', undefined);
        await queryRunner.query('ALTER TABLE `employees` DROP FOREIGN KEY `FK_37fe5168e0e0d65295042d47ea4`', undefined);
        await queryRunner.query('ALTER TABLE `employees` DROP FOREIGN KEY `FK_4d493f3a20ddc4d8faf6078bf95`', undefined);
        await queryRunner.query('ALTER TABLE `employees` DROP FOREIGN KEY `FK_678a3540f843823784b0fe4a4f2`', undefined);
        await queryRunner.query('ALTER TABLE `accounts` DROP FOREIGN KEY `FK_3ab689e515e134445a81873f87b`', undefined);
        await queryRunner.query('ALTER TABLE `schedules` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `schedules` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `rules` CHANGE `description` `description` text NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `rules` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `rules` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `requests` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `requests` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `reports` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `reports` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `attendances` CHANGE `meta` `meta` json NOT NULL', undefined);
        await queryRunner.query('ALTER TABLE `attendances` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `attendances` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `npwp_id` `npwp_id` varchar(20) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `bpjs_id` `bpjs_id` varchar(20) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `created_by` `created_by` varchar(255) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `position_id` `position_id` varchar(255) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `area_id` `area_id` varchar(255) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `group_id` `group_id` varchar(255) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `department_id` `department_id` varchar(255) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `active_date` `active_date` datetime NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `address` `address` text NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `employees` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `employees` ADD CONSTRAINT `FK_43d76ca7eecf9373241e2e890fb` FOREIGN KEY (`created_by`) REFERENCES `accounts`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `employees` ADD CONSTRAINT `FK_8b14204e8af5e371e36b8c11e1b` FOREIGN KEY (`position_id`) REFERENCES `positions`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `employees` ADD CONSTRAINT `FK_37fe5168e0e0d65295042d47ea4` FOREIGN KEY (`area_id`) REFERENCES `areas`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `employees` ADD CONSTRAINT `FK_4d493f3a20ddc4d8faf6078bf95` FOREIGN KEY (`group_id`) REFERENCES `groups`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `employees` ADD CONSTRAINT `FK_678a3540f843823784b0fe4a4f2` FOREIGN KEY (`department_id`) REFERENCES `departments`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `reward_deductions` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `reward_deductions` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `leaves` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `leaves` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `payslips` DROP COLUMN `meta`', undefined);
        await queryRunner.query('ALTER TABLE `payslips` ADD `meta` longtext COLLATE "utf8mb4_bin" NOT NULL', undefined);
        await queryRunner.query('ALTER TABLE `payslips` DROP COLUMN `reward`', undefined);
        await queryRunner.query('ALTER TABLE `payslips` ADD `reward` longtext COLLATE "utf8mb4_bin" NOT NULL', undefined);
        await queryRunner.query('ALTER TABLE `payslips` DROP COLUMN `deduction`', undefined);
        await queryRunner.query('ALTER TABLE `payslips` ADD `deduction` longtext COLLATE "utf8mb4_bin" NOT NULL', undefined);
        await queryRunner.query('ALTER TABLE `payslips` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `payslips` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `departments` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `departments` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `branchs` CHANGE `telp` `telp` varchar(15) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `branchs` CHANGE `postal_code` `postal_code` varchar(6) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `branchs` CHANGE `address` `address` text NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `branchs` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `branchs` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `accounts` CHANGE `branch_id` `branch_id` varchar(255) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `accounts` CHANGE `avatar` `avatar` varchar(255) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `accounts` CHANGE `last_name` `last_name` varchar(255) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `accounts` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `accounts` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `accounts` ADD CONSTRAINT `FK_3ab689e515e134445a81873f87b` FOREIGN KEY (`branch_id`) REFERENCES `branchs`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION', undefined);
        await queryRunner.query('ALTER TABLE `account_roles` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `account_roles` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `roles` CHANGE `description` `description` varchar(255) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `roles` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `roles` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `role_permissions` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `role_permissions` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `permissions` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `permissions` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `account_permissions` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `account_permissions` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `areas` CHANGE `bonus` `bonus` varchar(15) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `areas` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `areas` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `positions` CHANGE `bonus` `bonus` varchar(15) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `positions` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `positions` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `groups` DROP COLUMN `schedule`', undefined);
        await queryRunner.query('ALTER TABLE `groups` ADD `schedule` longtext COLLATE "utf8mb4_bin" NOT NULL', undefined);
        await queryRunner.query('ALTER TABLE `groups` CHANGE `day_salary` `day_salary` varchar(15) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `groups` CHANGE `week_salary` `week_salary` varchar(15) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `groups` CHANGE `base_salary` `base_salary` varchar(15) NULL DEFAULT \'NULL\'', undefined);
        await queryRunner.query('ALTER TABLE `groups` CHANGE `updated_at` `updated_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
        await queryRunner.query('ALTER TABLE `groups` CHANGE `created_at` `created_at` datetime(6) NULL DEFAULT \'current_timestamp(6)\'', undefined);
    }

}
